# https://woodpecker-ci.org/docs/usage/cron

when:
  - event: cron
    cron: "update-dwproton"
  - event: manual

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1

steps:
  update:
    image: nixos/nix:2.32.8
    commands:
      - export NIX_CONFIG="experimental-features = nix-command flakes"
      - nix run .#update-dwproton
      - |
        if git diff --quiet -- pkgs/dwproton-bin/default.nix; then
          echo "no update, nothing to push"
          exit 0
        fi

        nix build .#dwproton-bin -L

        NEW_VERSION=$(nix eval --raw .#dwproton-bin.version)

        mkdir -p ~/.ssh
        echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan codeberg.org >> ~/.ssh/known_hosts 2>/dev/null

        git config user.name "woodpecker-ci"
        git config user.email "ci@kernvoid.com"
        git add pkgs/dwproton-bin/default.nix
        git commit -m "dwproton: bump to $NEW_VERSION"
        git remote set-url origin git@codeberg.org:kernvoid/nix-dwproton.git
        git push origin HEAD:main
    environment:
      SSH_DEPLOY_KEY:
        from_secret: ssh_deploy_key